disabled_rules:
   - multiple_closures_with_trailing_closure
   - switch_case_alignment
   - cyclomatic_complexity
   - large_tuple
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - fastlane
line_length: 200
identifier_name:
   min_length: # only min_length
     warning: 1
   excluded: # excluded via string array
     - id
     - URL
     - GlobalAPIKey