# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "com.unknown-studios.YourKitchen" # The bundle identifier of your app
username "markus@unknown-studios.com" # your Apple ID user


ipa "./build/YourKitchen.ipa"

#screenshots_path "./fastlane/screenshots"


