# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPad Pro (12.9-inch) (2nd generation)"
])
languages([
  "en-US",
  "da"
])

# The name of the scheme which contains the UI Tests
scheme("Snapshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)
concurrent_simulators(false)

override_status_bar(true)