name: build_ios

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build and deploy to testflight
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v1
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Bundle Install
        run: bundle install
      - name: Setup Firebase
        run: 'echo "$GOOGLE_PLIST" > GoogleService-Info.plist; mv ./GoogleService-Info.plist ./YourKitchen/Misc/'
        shell: bash
        env:
          GOOGLE_PLIST: ${{secrets.GOOGLE_PLIST}}
      - name: Set Appstore Connect User
        run: bundle exec fastlane fastlane-credentials add --password ${{ secrets.FASTLANE_PASSWORD }} --username ${{ secrets.FASTLANE_USER }} 
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      - name: Fastlane Setup
        run: bundle exec fastlane setup
        env:
          CI_KEYCHAIN_NAME: ${{ secrets.CI_KEYCHAIN_NAME }}
          CI_KEYCHAIN_PASSWORD: ${{ secrets.CI_KEYCHAIN_PASSWORD }}
      - name: Fastlane Deploy to Testflight
        run: bundle exec fastlane github_test
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          CI_KEYCHAIN_NAME: ${{ secrets.CI_KEYCHAIN_NAME }}
          CI_KEYCHAIN_PASSWORD: ${{ secrets.CI_KEYCHAIN_PASSWORD }}
          GIT_ACCESS: ${{ secrets.GIT_ACCESS }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }} # Just for upload (To be sure)
